"""Pre-fit gate: opponent-graph coverage over the roster-map set.

A rating model can only put two teams on one comparable scale if the opponent graph connects them,
and can only compare regions if there are cross-region edges. This reports, before any fitting:
nodes, edges, connected components + largest-component coverage of the 16 TI teams, cross-region
links among the 16, and each TI team's opponent breadth. A disconnected graph or few cross-region
edges is a flag to lean on the market there, not the model (see backtest-protocol.md sec 6).

Reads processed/roster_matches.csv + raw/promatches_scan.json + inputs/canonical_identity.csv.
Writes docs/opponent-graph.md (tracked). Run: python -m ti_predict.opponent_graph
"""
import csv
import json
import os
from collections import defaultdict

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TI = os.path.join(REPO, "data", "ti2026")
DOCS = os.path.join(REPO, "docs")


def _read(p):
    with open(p, encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


class UF:
    def __init__(self): self.p = {}
    def find(self, x):
        self.p.setdefault(x, x)
        while self.p[x] != x:
            self.p[x] = self.p[self.p[x]]; x = self.p[x]
        return x
    def union(self, a, b): self.p[self.find(a)] = self.find(b)


def main():
    scan = {m["match_id"]: m for m in json.load(open(os.path.join(TI, "raw", "promatches_scan.json"), encoding="utf-8"))}
    matches = _read(os.path.join(TI, "processed", "roster_matches.csv"))
    canon = _read(os.path.join(TI, "inputs", "canonical_identity.csv"))

    id2org, id2region = {}, {}
    for r in canon:
        for sid in (r["source_team_ids"] or "").split("|"):
            if sid:
                id2org[int(sid)] = r["organization"]; id2region[int(sid)] = r["region"]

    edges = set()                       # frozenset({a,b})
    nodes = set()
    opp_by_org = defaultdict(set)       # org -> set of opponent team_ids
    uf = UF()
    for m in matches:
        sc = scan.get(int(m["match_id"]))
        if not sc:
            continue
        ours = m["source_team_id"]
        opp = sc["dire_team_id"] if m["side"] == "rad" else sc["radiant_team_id"]
        if not ours or not opp:
            continue
        ours, opp = int(ours), int(opp)
        nodes.add(ours); nodes.add(opp)
        edges.add(frozenset((ours, opp))); uf.union(ours, opp)
        org = id2org.get(ours)
        if org:
            opp_by_org[org].add(opp)

    # components
    comp = defaultdict(set)
    for n in nodes:
        comp[uf.find(n)].add(n)
    comps = sorted(comp.values(), key=len, reverse=True)
    our_ids = set(id2org)
    biggest = comps[0] if comps else set()
    our_in_big = {id2org[i] for i in biggest & our_ids}

    # cross-region edges among the 16
    xreg = defaultdict(int)
    for e in edges:
        a, b = tuple(e) if len(e) == 2 else (next(iter(e)), next(iter(e)))
        if a in our_ids and b in our_ids:
            ra, rb = id2region[a], id2region[b]
            oa, ob = id2org[a], id2org[b]
            if oa != ob and ra != rb:
                xreg["-".join(sorted((ra, rb)))] += 1

    # per-org opponent breadth
    breadth = {}
    for r in canon:
        org = r["organization"]
        opps = opp_by_org.get(org, set())
        ti_opps = {id2org[o] for o in opps if o in our_ids and id2org[o] != org}
        breadth[org] = (len(opps), len(ti_opps))

    L = ["# Opponent-graph coverage (pre-fit gate)", "",
         f"Over {len(matches)} roster-maps. Generated by `ti_predict/opponent_graph.py`.", "",
         f"- **Nodes (distinct teams incl. opponents):** {len(nodes)}",
         f"- **Edges (distinct matchup pairs):** {len(edges)}",
         f"- **Connected components:** {len(comps)}; largest has {len(biggest)} teams",
         f"- **TI teams in the largest component:** {len(our_in_big)}/16"
         + ("" if len(our_in_big) == 16 else f"  (MISSING: {sorted(set(id2org.values())-our_in_big)})"),
         "", "## Cross-region links among the 16 (direct matchups, different regions)"]
    if xreg:
        for k, v in sorted(xreg.items(), key=lambda x: -x[1]):
            L.append(f"- {k}: {v}")
    else:
        L.append("- NONE — regions only linked indirectly via shared opponents (flag).")
    L += ["", "## Per-TI-team opponent breadth", "", "| team | distinct opponents | of which TI teams |",
          "|------|-----:|-----:|"]
    for org in sorted(breadth):
        d, t = breadth[org]
        L.append(f"| {org} | {d} | {t} |")
    total_xreg = sum(xreg.values())
    L += ["", "## Read",
          f"Graph is {'CONNECTED — all 16 on one scale' if len(our_in_big)==16 and len(comps)>=1 else 'FRAGMENTED — flag'}. "
          f"{total_xreg} direct cross-region matchups among the 16"
          + (" — regions are directly linked (Elo comparable across regions)."
             if total_xreg >= 10 else " — sparse; prefer market anchoring for cross-region matchups.")]
    out = "\n".join(L) + "\n"
    with open(os.path.join(DOCS, "opponent-graph.md"), "w", encoding="utf-8") as fh:
        fh.write(out)
    print(out)


if __name__ == "__main__":
    main()
